name: Build MindTheGapps

on:
  workflow_dispatch:

jobs:
  matrix:
    name: Generate build matrix
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.setup.outputs.matrix }}
    steps:
      - name: Generate build matrix
        id: setup
        uses: actions/github-script@v6
        with:
          script: |
            let matrix = {};
            matrix.arch = ["arm64", "x86_64"]
            core.setOutput("matrix", JSON.stringify(matrix));

  build:
    name: Build MindTheGapps v13.0 ${{ matrix.arch }}
    runs-on: ubuntu-22.04
    needs: matrix
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:

      - name: Clone repository
        run: git clone --depth=1 -b tau https://gitlab.com/MindTheGapps/vendor_gapps.git/

      - name: Build
        working-directory: vendor_gapps
        run: |
          if [ -d overlay ]; then
            sudo apt-get install -y aapt zipalign
            mkdir -p common/proprietary/product/overlay
            sed -i -e '/overlay/d' build/gapps.sh
            sed -i -e '/RROs/d' build/gapps.sh
            echo "Compiling RROs"
            find overlay -maxdepth 1 -mindepth 1 -type d -print0 | while IFS= read -r -d '' dir
            do
                echo "Building ${dir/overlay\//}"
                aapt package -M "$dir"/AndroidManifest.xml -S "$dir"/res/ -I /usr/local/lib/android/sdk/platforms/android-33/android.jar -F "${dir/overlay\//}".apk.u
                zipalign -v 4 "${dir/overlay\//}".apk.u "${dir/overlay\//}".apk.s
                java -jar build/sign/signapk.jar build/sign/testkey.x509.pem build/sign/testkey.pk8 "${dir/overlay\//}".apk.s "${dir/overlay\//}".apk
            done
            mv -v *.apk common/proprietary/product/overlay
          fi
          sed -i -e 's/_%H%M%S//' build/gapps.sh
          echo "date=$(date -u +%Y%m%d)" >> $GITHUB_ENV
          bash build/gapps.sh ${{ matrix.arch }}
          
      - name: Some minor fixes
        working-directory: vendor_gapps/out
        run: |
         zip -d *.zip "system/addon.d/*" "system/product/app/*Exchange*/*" "system/product/app/*CalendarSync*" "system/product/etc/default-permissions/*mtg*" "system/product/etc/permissions/*dialer*" "system/product/etc/sysconfig/*build*" "system/product/framework/*" "system/product/lib*/*" "system/product/priv-app/AndroidAuto*/*" "system/system_ext/priv-app/SetupWizard/*"
         zip -g *.zip "../../common/gapps/product/overlay/GoogleWebViewOverlay.apk"
      
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ env.date }}
          fail_on_unmatched_files: true
          files: |
            vendor_gapps/out/*
          body: Updated on ${{ env.date }}
