name: Build MindTheGapps

on:
  workflow_dispatch:
    inputs:
      test:
        description: "Test mode"
        required: true
        default: false
        type: boolean

jobs:
  matrix:
    name: Generate build matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup.outputs.matrix }}
    steps:
      - name: Generate build matrix
        id: setup
        uses: actions/github-script@v6
        with:
          script: |
            let matrix = {};
            matrix.arch = ["arm64", "x86_64"]
            core.setOutput("matrix", JSON.stringify(matrix));

  build:
    name: 13.0.0-${{ matrix.arch }}
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone repository
        run: git clone --depth=1 -b tau https://gitlab.com/MindTheGapps/vendor_gapps.git/

      - name: Build
        working-directory: vendor_gapps
        run: |
          echo "date=$(date -u +%Y%m%d)" >> $GITHUB_ENV
          cp -f ../build.sh build/gapps.sh
          ./build/gapps.sh ${{ matrix.arch }}

      - name: Upload
        if: github.event.inputs.test == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: Built_WSA-${{ matrix.arch }}-${{ env.date }}
          path: vendor_gapps/out/*
          if-no-files-found: warn

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: github.event.inputs.test != 'true'
        with:
          tag_name: ${{ env.date }}
          fail_on_unmatched_files: true
          files: vendor_gapps/out/*.zip
          body: Updated on ${{ env.date }}
